# Generated by Django 3.1.1 on 2020-12-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='local', max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
