# Generated by Django 3.1.1 on 2020-12-11 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0002_auto_20201211_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.CharField(default='null', max_length=30)),
                ('chipset', models.CharField(default='null', max_length=30)),
                ('gpu', models.CharField(default='null', max_length=30)),
                ('technology', models.CharField(default='null', max_length=30)),
                ('size', models.CharField(default='null', max_length=30)),
                ('resolution', models.CharField(default='null', max_length=30)),
                ('ram', models.IntegerField(default=0)),
                ('hardDisk', models.IntegerField(default=0)),
                ('WLAN', models.CharField(default='null', max_length=30)),
                ('BlueTooth', models.CharField(default='null', max_length=30)),
                ('GPS', models.CharField(default='null', max_length=30)),
                ('Radio', models.CharField(default='null', max_length=30)),
                ('sensors', models.CharField(default='null', max_length=30)),
                ('audio', models.CharField(default='null', max_length=30)),
                ('browser', models.CharField(default='null', max_length=30)),
                ('messaging', models.CharField(default='null', max_length=30)),
                ('games', models.CharField(default='null', max_length=30)),
                ('capacity', models.CharField(default='null', max_length=30)),
                ('fastCharging', models.CharField(default='null', max_length=30)),
                ('price', models.IntegerField(default=0)),
                ('ratingStars', models.IntegerField(default=0)),
                ('noOfReviews', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='shopApp/images')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopApp.brand')),
            ],
        ),
    ]
