# Generated by Django 3.1.1 on 2020-12-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0006_auto_20201211_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='hardDisk',
            field=models.CharField(default='null', max_length=80),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ram',
            field=models.CharField(default='null', max_length=80),
        ),
    ]
