# Generated by Django 3.1.1 on 2020-12-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0007_auto_20201212_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='desc',
            field=models.CharField(default='Description....', max_length=1000),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ratingStars',
            field=models.FloatField(default=0),
        ),
    ]
