# Generated by Django 3.1.1 on 2020-12-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0008_auto_20201212_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='desc',
            field=models.CharField(default='Description....', max_length=2500),
        ),
    ]
